name: normal_julia_sets
description: Normal Julia Sets generator
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bloc: ^8.0.3
  cancelable_compute: ^1.2.0
  cloud_firestore: ^3.1.18
  equatable: ^2.0.3
  firebase_auth: ^3.3.20
  firebase_core: ^1.18.0
  firebase_storage: ^10.2.18
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  flutter_localizations:
    sdk: flutter
  google_sign_in: ^5.3.3
  intl: ^0.17.0
  path_provider: ^2.0.9

dev_dependencies:
  bloc_test: ^9.0.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  mocktail: ^0.3.0
  very_good_analysis: ^2.4.0

flutter:
  uses-material-design: true
  generate: true
